'use client';

import { useState } from 'react';
import { 
  FileText, Search, ShieldCheck, Award, HardHat, Calendar
} from 'lucide-react';

export default function CertificateLogsPage() {
  const [logs, setLogs] = useState([
    {
      id: 'LOG-849201',
      certId: 'GS-CERT-VND-2026-081',
      recipient: 'Nikhil Mehta (Gaya Electricals)',
      type: 'Vendor Certificate',
      generatedBy: 'Super Admin',
      status: 'ISSUED & SIGNED',
      timestamp: '20 Jul 2026, 04:15 PM'
    },
    {
      id: 'LOG-849202',
      certId: 'GS-CERT-LBR-2026-101',
      recipient: 'Ramesh Kumar (Electrician)',
      type: 'Labour Certificate',
      generatedBy: 'System Administrator',
      status: 'ISSUED & SIGNED',
      timestamp: '18 Jul 2026, 11:30 AM'
    },
    {
      id: 'LOG-849203',
      certId: 'GS-CERT-VND-2026-082',
      recipient: 'Rajesh Kumar (Gaya Medical)',
      type: 'Vendor Certificate',
      generatedBy: 'Super Admin',
      status: 'ISSUED & SIGNED',
      timestamp: '15 Jul 2026, 02:45 PM'
    }
  ]);

  const [search, setSearch] = useState('');

  const filtered = logs.filter(l => 
    l.certId.toLowerCase().includes(search.toLowerCase()) ||
    l.recipient.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12 font-sans">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div>
          <h1 className="text-2xl font-black text-slate-900 dark:text-white">Certificate Issuance Audit Logs</h1>
          <p className="text-slate-500 text-xs mt-1">Track digital signatures, certificate printing history, and issuance logs.</p>
        </div>
      </div>

      {/* Search & Table */}
      <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-800 overflow-hidden">
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <div className="relative w-full max-w-sm">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input 
              type="text" 
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search by certificate ID or recipient name..." 
              className="w-full pl-9 pr-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 text-xs font-medium outline-none focus:border-indigo-500 text-slate-900 dark:text-white"
            />
          </div>
          <span className="text-xs font-bold text-slate-500">
            Total Logs: <strong className="text-indigo-600 dark:text-indigo-400">{filtered.length}</strong>
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/60 text-[10px] uppercase font-black tracking-wider text-slate-400">
                <th className="py-3.5 px-6">Log ID / Cert ID</th>
                <th className="py-3.5 px-6">Recipient & Certificate Type</th>
                <th className="py-3.5 px-4">Generated By</th>
                <th className="py-3.5 px-4">Status</th>
                <th className="py-3.5 px-6 text-right">Timestamp</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {filtered.map(l => (
                <tr key={l.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40 transition">
                  <td className="py-3.5 px-6 font-mono font-extrabold text-indigo-600 dark:text-indigo-400">
                    <div>{l.certId}</div>
                    <div className="text-[10px] text-slate-400 font-mono">{l.id}</div>
                  </td>
                  <td className="py-3.5 px-6">
                    <div className="font-extrabold text-slate-900 dark:text-white text-sm">{l.recipient}</div>
                    <div className="text-[11px] text-slate-400 font-medium">{l.type}</div>
                  </td>
                  <td className="py-3.5 px-4 font-bold text-slate-700 dark:text-slate-300">{l.generatedBy}</td>
                  <td className="py-3.5 px-4">
                    <span className="px-2.5 py-1 rounded-full text-[10px] font-black uppercase bg-emerald-500/10 text-emerald-600 border border-emerald-500/20">
                      ● {l.status}
                    </span>
                  </td>
                  <td className="py-3.5 px-6 text-right text-slate-500 font-medium">{l.timestamp}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
